#!/bin/sh
# convert light colors to breeze-dark colors

	#inkscape -f "$i" -e "${i%.*}.png"
	sed -i -e 's/#f2f2f2/#4d4d4d/g' "$1"
	sed -i -e 's/#31363b/#eff0f1/g' "$1"
	sed -i -e 's/#4f575f/#fcfcfc/g' "$1"
