#ifndef OKJVERSION_H
#define OKJVERSION_H

#define OKJ_VERSION_MAJOR 1
#define OKJ_VERSION_MINOR 4
#define OKJ_VERSION_BUILD 5
#define OKJ_VERSION_STRING "1.4.5"
#define OKJ_VERSION_BRANCH "stable"

#endif //OKJVERSION_H
