#ifndef OKJVERSION_H
#define OKJVERSION_H

#define OKJ_VERSION_MAJOR 1
#define OKJ_VERSION_MINOR 7
#define OKJ_VERSION_BUILD 68
#define OKJ_VERSION_STRING "1.7.68"
#define OKJ_VERSION_BRANCH "unstable"

#endif //OKJVERSION_H
