#ifndef OKJVERSION_H
#define OKJVERSION_H

#define OKJ_VERSION_MAJOR 2
#define OKJ_VERSION_MINOR 0
#define OKJ_VERSION_BUILD 8
#define OKJ_VERSION_STRING "2.0.8"
#define OKJ_VERSION_BRANCH "release"

#endif //OKJVERSION_H
