#ifndef OKJVERSION_H
#define OKJVERSION_H

#define OKJ_VERSION_MAJOR 1
#define OKJ_VERSION_MINOR 9
#define OKJ_VERSION_BUILD 84
#define OKJ_VERSION_STRING "1.9.84"
#define OKJ_VERSION_BRANCH "unstable"

#endif //OKJVERSION_H
