name: linux build in docker
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: debian
          - name: fedora
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "tagdate=$(date +%Y%m%d)" >> $GITHUB_ENV

      - uses: docker/build-push-action@v5
        name: docker image build
        with:
          file: Dockerfile.${{ matrix.name }}
            #push: ${{ github.event_name != 'pull_request' }}
          push: true
          tags: ghcr.io/openkj/openkj:${{ matrix.name }}-${{ env.tagdate }}

